// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type User struct {
	ID             string
	CreatedAt      string
	UpdatedAt      string
	Name           string
	Email          sql.NullString
	HashedPassword string
	ApiKey         string
}
