// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Communication struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Model     string
	Question  string
	Reply     sql.NullString
	UserID    string
}

type User struct {
	ID             string
	CreatedAt      string
	UpdatedAt      string
	Login          string
	Email          sql.NullString
	HashedPassword string
	ApiKey         string
}
